### ISSUE TITLE
Planejamento Backend

### ISSUE THREAD

**Issue by MMGSN** [dami-pie/api#4]
Definição de tecnologias utilizadas no back.

**Comment by MMGSN** [comment]
- [ ] Definição e estudo da linguagem
- [ ] Definição e estudo do broker
- [ ] Definição do banco de dados

**Comment by Sevlak** [comment]
Conforme conversado no discord, decidimos continuar com Go (https://go.dev/) como linguagem, RabbitMQ (https://www.rabbitmq.com/) como o broker e MySQL (https://www.mysql.com/) como banco de dados.
